version: '3'

services:

  postgres:
    image: postgres:latest
    container_name: postgres
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 3000M
    env_file:
      - ./pg/database.env
    ports:
      - "5432:5432"

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    ports:
      - "27017:27017"
