openapi: 3.0.3
info:
  description: HW008 openApi3.0 trial
  title: HW008 openApi3.0 trial
  version: 1.0.0
  contact:
    url: https://github.com/rodkevich/go-course/pulls
tags:
  - name: save
    description: saving data operations
servers:
  - url: http://localhost:{port}/{basePath}
    description: HW008 development API server
    variables:
      port:
        enum:
          - '5051'
          - '8081'
        default: '5051'
      basePath:
        # open meaning there is the opportunity to use special
        # base paths as assigned by the provider, default is `v2`
        default: v1
paths:
  "/save-token":
    post:
      tags:
        - save
      summary: ask to save a token to map
      parameters:
        - name: createdAt
          in: query
          required: true
          description: Token life-time [start]
          schema:
            type: string
            format: 'date-time'
            description: "ISO8601"
            example: "2021-08-19T18:38:33+03:00"
        - name: expiredAt
          in: query
          required: true
          description: Token life-time [end]
          schema:
            type: string
            format: 'date-time'
            description: "ISO8601"
            example: "2021-08-29T18:38:33+03:00"
        - name: token
          in: query
          required: true
          description: Token name to save as
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SaveTokenRequest"
        description: Request for token saving
        required: false
      responses:
        "200":
          description: OK response (return hash if i'll have time)
          content:
            application/json:
              schema:
                type: string
        "500":
          description: Ошибка запроса
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Error:
      type: object
      required:
        - payload
        - status
      properties:
        status:
          type: string
          default: Error
        payload:
          type: object
          properties:
            message:
              type: string
            code:
              $ref: "#/components/schemas/ErrorCodes"
    SaveTokenRequest:
      type: object
      required:
        - payload
      properties:
        payload:
          type: object
          properties:
            token:
              type: string
            operation:
              $ref: "#/components/schemas/OperationsType"
    # Just to try how those enums work
    OperationsType:
      type: string
      enum:
        - save
    ErrorCodes:
      type: string
      enum:
        - 1
        - 2
        - 3
